import * as fs from 'fs'
import * as path from 'path'

import inquirer from 'inquirer'

import { GwitError } from '../types'
import { runArgsSafe } from '../lib/shell'
import { ui } from '../lib/ui'
import { isGitRepo, getMainWorktreePath } from '../core/git'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface InitOptions {
  /** When true, overwrite existing hook files. */
  force: boolean
}

interface StackSelection {
  packageManager: 'npm' | 'pnpm' | 'yarn' | 'bun' | null
  database: 'postgres' | 'mysql' | null
  appName: string
  redis: boolean
  dockerCompose: boolean
  writeEnvBlock: boolean
  extraSetup: string[]
  extraCleanup: string[]
}

// ─── Constants ────────────────────────────────────────────────────────────────

const GWITINCLUDE_FILE = '.gwitinclude'
const GWITCOMMAND_FILE = '.gwitcommand'
const GWITCLEANUP_FILE = '.gwitcleanup'

const INCLUDE_HEADER = [
  '# Files and directories to copy into each new worktree.',
  '# Generated by gwit init — edit freely.',
  '# Rules: literal paths only, one per line, # for comments.',
  '# Only gitignored, non-tracked paths are copied (tracked files are already in the worktree).',
].join('\n')

const COMMAND_HEADER = [
  '# Commands run inside the new worktree after gwit create.',
  '# Generated by gwit init — edit freely.',
  '#',
  '# Available variables:',
  "#   $GWIT_PORT        — unique port for this worktree's dev server",
  '#   $GWIT_DB_SUFFIX   — database name suffix    (e.g. _feature_auth)',
  '#   $GWIT_INDEX       — stable integer index    (e.g. 2) — safe for Redis DB number',
  '#   $GWIT_SLUG        — filesystem/Docker-safe slug  (e.g. feature_auth)',
  '#   $GWIT_BRANCH      — full branch name         (e.g. feature/auth)',
  '#   $GWIT_WORKTREE_PATH / $GWIT_MAIN_PATH',
].join('\n')

const CLEANUP_HEADER = [
  '# Commands run inside the worktree before gwit remove.',
  '# Generated by gwit init — edit freely.',
  '# All $GWIT_* variables are available.',
].join('\n')

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Reads the app name from package.json `name` field, stripping any npm scope
 * prefix. Falls back to the repo directory name.
 *
 * @param mainPath - Absolute path to the main worktree.
 * @returns A plain string suitable for use as a database name prefix.
 */
export function _detectAppName(mainPath: string): string {
  const pkgPath = path.join(mainPath, 'package.json')
  if (fs.existsSync(pkgPath)) {
    try {
      const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as { name?: string }
      if (pkg.name && pkg.name.trim().length > 0) {
        // Strip npm scope (@org/name → name) so DB names stay clean
        return pkg.name.replace(/^@[^/]+\//, '').trim()
      }
    } catch {
      // Fall through to dirname fallback
    }
  }
  return path.basename(mainPath)
}

/**
 * Auto-detects the package manager by checking for lock files in the repo root.
 *
 * @param mainPath - Absolute path to the main worktree.
 * @returns The detected package manager name, or null if no JS project found.
 */
export function _detectPackageManager(mainPath: string): 'npm' | 'pnpm' | 'yarn' | 'bun' | null {
  if (fs.existsSync(path.join(mainPath, 'bun.lockb'))) return 'bun'
  if (fs.existsSync(path.join(mainPath, 'pnpm-lock.yaml'))) return 'pnpm'
  if (fs.existsSync(path.join(mainPath, 'yarn.lock'))) return 'yarn'
  if (fs.existsSync(path.join(mainPath, 'package.json'))) return 'npm'
  return null
}

/**
 * Returns all gitignored files and directories at the repo root by running
 * `git ls-files --others --ignored --exclude-standard --directory`.
 *
 * @param mainPath - Absolute path to the main worktree.
 * @returns Array of relative path strings (directories include trailing `/`).
 */
function scanGitignored(mainPath: string): string[] {
  const result = runArgsSafe(
    'git',
    ['ls-files', '--others', '--ignored', '--exclude-standard', '--directory'],
    { cwd: mainPath }
  )
  if (!result.success) return []
  return result.stdout
    .split('\n')
    .map((l) => l.trim())
    .filter((l) => l.length > 0)
}

/**
 * Writes content to a hook file. Skips without writing if the file already
 * exists and `force` is false.
 *
 * @param filePath - Absolute path to write.
 * @param content - File content.
 * @param force - When true, overwrites an existing file.
 * @returns 'written' or 'skipped'.
 */
function writeHookFile(filePath: string, content: string, force: boolean): 'written' | 'skipped' {
  if (fs.existsSync(filePath) && !force) return 'skipped'
  fs.writeFileSync(filePath, content, 'utf-8')
  return 'written'
}

/**
 * Prompts for a sequence of shell commands, stopping when the user submits an
 * empty line.
 *
 * @param firstMessage - Prompt text for the first command.
 * @param continueMessage - Prompt text for subsequent commands.
 * @returns Array of non-empty command strings in entry order.
 */
async function collectCommands(firstMessage: string, continueMessage: string): Promise<string[]> {
  const commands: string[] = []
  let collecting = true

  while (collecting) {
    const { cmd } = await inquirer.prompt<{ cmd: string }>([
      {
        type: 'input',
        name: 'cmd',
        message: commands.length === 0 ? firstMessage : continueMessage,
      },
    ])
    if (cmd.trim()) {
      commands.push(cmd.trim())
    } else {
      collecting = false
    }
  }

  return commands
}

// ─── Content builders ─────────────────────────────────────────────────────────

/**
 * Builds the content string for `.gwitinclude`.
 * Exported with `_` prefix for unit testing only.
 *
 * @param entries - Relative paths to include (one per line).
 * @returns File content string.
 */
export function _buildIncludeContent(entries: string[]): string {
  if (entries.length === 0) return `${INCLUDE_HEADER}\n`
  return `${INCLUDE_HEADER}\n\n${entries.join('\n')}\n`
}

/**
 * Builds the content string for `.gwitcommand` from the stack selection.
 * Exported with `_` prefix for unit testing only.
 *
 * @param appName - App name used as the database name prefix.
 * @param sel - Stack service selections from the wizard.
 * @returns File content string.
 */
export function _buildCommandContent(appName: string, sel: StackSelection): string {
  const lines: string[] = [COMMAND_HEADER, '']
  const pm = sel.packageManager ?? 'npm'

  // ── Package install ──────────────────────────────────────────────────────

  if (sel.packageManager) {
    lines.push(`${sel.packageManager} install`)
  }

  // ── Database provisioning ────────────────────────────────────────────────

  if (sel.database === 'postgres') {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push(`createdb ${appName}$GWIT_DB_SUFFIX`)
    lines.push(`${pm} run db:migrate`)
  } else if (sel.database === 'mysql') {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push(`mysql -e "CREATE DATABASE IF NOT EXISTS ${appName}$GWIT_DB_SUFFIX;"`)
    lines.push(`${pm} run db:migrate`)
  }

  // ── Docker Compose ───────────────────────────────────────────────────────

  if (sel.dockerCompose) {
    if (lines[lines.length - 1] !== '') lines.push('')
    // appName is a fixed string at generation time; GWIT_SLUG varies per worktree
    lines.push(`COMPOSE_PROJECT_NAME=${appName}_$GWIT_SLUG docker compose up -d`)
  }

  // ── .env block ───────────────────────────────────────────────────────────

  if (sel.writeEnvBlock) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push('# Append gwit variables to .env (place these last so they override copied values)')
    lines.push(`echo "PORT=$GWIT_PORT" >> .env`)
    if (sel.database === 'postgres') {
      lines.push(`echo "DATABASE_URL=postgres://localhost/${appName}$GWIT_DB_SUFFIX" >> .env`)
    } else if (sel.database === 'mysql') {
      lines.push(`echo "DATABASE_URL=mysql://localhost/${appName}$GWIT_DB_SUFFIX" >> .env`)
    }
    if (sel.redis) {
      lines.push(`echo "REDIS_URL=redis://localhost:6379/$GWIT_INDEX" >> .env`)
    }
  }

  // ── Extra commands ───────────────────────────────────────────────────────

  if (sel.extraSetup.length > 0) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push(...sel.extraSetup)
  }

  // Trim trailing blank lines
  while (lines[lines.length - 1] === '') lines.pop()
  return lines.join('\n') + '\n'
}

/**
 * Builds the content string for `.gwitcleanup` from the stack selection.
 * Exported with `_` prefix for unit testing only.
 *
 * @param appName - App name used as the database name prefix.
 * @param sel - Stack service selections from the wizard.
 * @returns File content string.
 */
export function _buildCleanupContent(appName: string, sel: StackSelection): string {
  const lines: string[] = [CLEANUP_HEADER, '']

  // ── Database teardown ────────────────────────────────────────────────────

  if (sel.database === 'postgres') {
    lines.push(`dropdb --if-exists ${appName}$GWIT_DB_SUFFIX`)
  } else if (sel.database === 'mysql') {
    lines.push(`mysql -e "DROP DATABASE IF EXISTS ${appName}$GWIT_DB_SUFFIX;"`)
  }

  // ── Docker Compose teardown ──────────────────────────────────────────────

  if (sel.dockerCompose) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push(`COMPOSE_PROJECT_NAME=${appName}_$GWIT_SLUG docker compose down -v`)
  }

  // ── Extra commands ───────────────────────────────────────────────────────

  if (sel.extraCleanup.length > 0) {
    if (lines[lines.length - 1] !== '') lines.push('')
    lines.push(...sel.extraCleanup)
  }

  // If nothing substantive was generated, add a placeholder so the file is
  // still useful as documentation of what could go here
  const hasContent = lines.some((l) => l.length > 0 && !l.startsWith('#'))
  if (!hasContent) {
    lines.push('# No teardown commands configured.')
    lines.push('# Examples: dropdb, docker compose down, rm -rf tmp/')
  }

  while (lines[lines.length - 1] === '') lines.pop()
  return lines.join('\n') + '\n'
}

// ─── Prompts ──────────────────────────────────────────────────────────────────

/**
 * Presents a checkbox of gitignored entries found at the repo root and returns
 * whichever ones the user selected. Pre-selects `.env*` files.
 *
 * @param mainPath - Absolute path to the main worktree.
 * @returns Array of selected relative paths.
 */
async function promptIncludeEntries(mainPath: string): Promise<string[]> {
  const found = scanGitignored(mainPath)

  if (found.length === 0) {
    ui.dim('  No gitignored entries found — .gwitinclude will be empty (edit it manually).')
    return []
  }

  const { entries } = await inquirer.prompt<{ entries: string[] }>([
    {
      type: 'checkbox',
      name: 'entries',
      message: 'Which gitignored files/dirs should be copied into each new worktree?',
      choices: found.map((entry) => ({
        name: entry,
        value: entry,
        // Pre-select .env* patterns — they almost always need copying
        checked: /^\.env/.test(entry),
      })),
    },
  ])

  return entries
}

/**
 * Runs the stack service selection prompts and collects extra commands.
 *
 * @param detectedPm - Package manager detected from lock files (used as default).
 * @param detectedAppName - App name from package.json or dirname (used as default).
 * @returns Complete StackSelection from the user's answers.
 */
async function promptStackSelection(
  detectedPm: 'npm' | 'pnpm' | 'yarn' | 'bun' | null,
  detectedAppName: string
): Promise<StackSelection> {
  // ── Package manager ──────────────────────────────────────────────────────

  const { packageManager } = await inquirer.prompt<{
    packageManager: 'npm' | 'pnpm' | 'yarn' | 'bun' | null
  }>([
    {
      type: 'list',
      name: 'packageManager',
      message: 'Package manager install step?',
      default: detectedPm ?? 'npm',
      choices: [
        { name: 'npm install', value: 'npm' },
        { name: 'pnpm install', value: 'pnpm' },
        { name: 'yarn install', value: 'yarn' },
        { name: 'bun install', value: 'bun' },
        { name: 'None — skip', value: null },
      ],
    },
  ])

  // ── Database ─────────────────────────────────────────────────────────────

  const { database } = await inquirer.prompt<{ database: 'postgres' | 'mysql' | null }>([
    {
      type: 'list',
      name: 'database',
      message: 'Database isolation?',
      choices: [
        { name: 'None', value: null },
        { name: 'PostgreSQL  (createdb / dropdb per worktree)', value: 'postgres' },
        { name: 'MySQL       (CREATE / DROP DATABASE per worktree)', value: 'mysql' },
      ],
    },
  ])

  let appName = detectedAppName
  if (database) {
    const answer = await inquirer.prompt<{ appName: string }>([
      {
        type: 'input',
        name: 'appName',
        message: `App name prefix for database naming  ("${detectedAppName}" → ${detectedAppName}$GWIT_DB_SUFFIX):`,
        default: detectedAppName,
        validate: (v: string) => v.trim().length > 0 || 'App name cannot be empty',
      },
    ])
    appName = answer.appName.trim()
  }

  // ── Redis ─────────────────────────────────────────────────────────────────

  const { redis } = await inquirer.prompt<{ redis: boolean }>([
    {
      type: 'confirm',
      name: 'redis',
      message: 'Redis isolation?  ($GWIT_INDEX as the DB number — supports up to 16 worktrees)',
      default: false,
    },
  ])

  // ── Docker Compose ────────────────────────────────────────────────────────

  const { dockerCompose } = await inquirer.prompt<{ dockerCompose: boolean }>([
    {
      type: 'confirm',
      name: 'dockerCompose',
      message: 'Docker Compose isolation?  (namespaces the full stack via COMPOSE_PROJECT_NAME)',
      default: false,
    },
  ])

  // ── .env block ────────────────────────────────────────────────────────────

  const { writeEnvBlock } = await inquirer.prompt<{ writeEnvBlock: boolean }>([
    {
      type: 'confirm',
      name: 'writeEnvBlock',
      message: 'Write $GWIT_* variables into .env at setup time?',
      default: true,
    },
  ])

  // ── Extra commands ────────────────────────────────────────────────────────

  const extraSetup = await collectCommands(
    'Any extra setup commands?  (e.g. "npm run seed", empty to skip)',
    'Another setup command?  (empty to finish)'
  )

  const extraCleanup = await collectCommands(
    'Any extra cleanup commands?  (e.g. "rm -rf tmp/", empty to skip)',
    'Another cleanup command?  (empty to finish)'
  )

  return {
    packageManager,
    database,
    appName,
    redis,
    dockerCompose,
    writeEnvBlock,
    extraSetup,
    extraCleanup,
  }
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Runs the gwit init wizard, interactively scaffolding `.gwitinclude`,
 * `.gwitcommand`, and `.gwitcleanup` for the current repository.
 *
 * Existing files are skipped unless `--force` is passed. The generated files
 * should be committed so every teammate gets the same isolation setup.
 *
 * @param options - Init options (force flag).
 */
export async function initCommand(options: InitOptions): Promise<void> {
  if (!isGitRepo()) {
    throw new GwitError('Not a git repository.', 'Run gwit init from inside a git repo.')
  }

  const mainPath = getMainWorktreePath()
  const detectedAppName = _detectAppName(mainPath)
  const detectedPm = _detectPackageManager(mainPath)

  console.log()
  ui.info(`Setting up gwit for ${ui.bold(path.basename(mainPath))}`)
  if (!options.force) {
    ui.dim('  Existing files are skipped — use --force to overwrite.')
  }
  console.log()

  // ── Step 1: .gwitinclude ──────────────────────────────────────────────────

  ui.step('.gwitinclude — files to copy into each new worktree')
  const entries = await promptIncludeEntries(mainPath)
  console.log()

  // ── Step 2: stack services ────────────────────────────────────────────────

  ui.step('.gwitcommand / .gwitcleanup — setup and teardown per worktree')
  const sel = await promptStackSelection(detectedPm, detectedAppName)
  console.log()

  // ── Write files ───────────────────────────────────────────────────────────

  const files = [
    { name: GWITINCLUDE_FILE, content: _buildIncludeContent(entries) },
    { name: GWITCOMMAND_FILE, content: _buildCommandContent(sel.appName, sel) },
    { name: GWITCLEANUP_FILE, content: _buildCleanupContent(sel.appName, sel) },
  ]

  for (const { name, content } of files) {
    const result = writeHookFile(path.join(mainPath, name), content, options.force)
    if (result === 'written') {
      ui.success(`  ${name}`)
    } else {
      ui.dim(`  ${name}  (skipped — already exists, use --force to overwrite)`)
    }
  }

  console.log()
  ui.success('Done! Commit these files so teammates get the same setup automatically.')
  ui.dim(`  git add ${GWITINCLUDE_FILE} ${GWITCOMMAND_FILE} ${GWITCLEANUP_FILE}`)
  console.log()
}
